version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: WindFarmMonitoring/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo
      - mqtt
    networks:
      - windfarm-network

  python-simulator:
    build:
      context: ./pythonSimulator 
    container_name: python-simulator
    depends_on:
      - mqtt
    networks:
      - windfarm-network
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - windfarm-network
    volumes:
      - mongo_data:/data/db

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1884:1883"
    networks:
      - windfarm-network
    volumes:
      - C:/Users/pauli/OneDrive/Pulpit/CLanguage/WindFarmMonitoring/WindFarmMonitoring/config/mosquitto.config:/mosquitto/config/mosquitto.conf

networks:
  windfarm-network:
    driver: bridge

volumes:
  mongo_data: